### PR TITLE
[GH-16110] Check if path is local path when checking denied files

### LINKED ISSUE #16110: hadoop test fails on export test on hdfs path
hadoop test fails on export test on hdfs path

`: Server error java.lang.IllegalArgumentException: Error: URI scheme is not "file" Request: POST /3/Frames/prostate.hex/export data: {'path': 'hdfs:///user/jenkins/tests/prostate_export_compressed.csv.gz', 'num_parts': '1', 'force': 'True', 'compression': 'gzip', 'separator': '44', 'header': 'True', 'quote_header': 'True', 'parallel': 'False', 'format': 'csv', 'write_checksum': 'True'}`

### PR DESCRIPTION
**Pull request by krasinski**
fix #16110

### CODE REVIEW

**Review by valenad1 — APPROVED** [review]
LGTM, please put it to 3.46.0 branch :)

File: h2o-core/src/main/java/water/persist/PersistManager.java [hunk 1]
```diff
@@ -849,12 +848,11 @@ public Persist getPersistForURI(URI uri) {
    * @return boolean
    */
   public boolean isFileAccessDenied(String path) {
+    if (isHdfsPath(path) || isGcsPath(path) || isS3Path(path)) {
```
Comment (mn-mikke) [inline h2o-core/src/main/java/water/persist/PersistManager.java:851]: what about nfs path? would't it be safer to check it just on `file:` schema instead of explicitly specifying the list of schemas that are ingored ?

**Review by mn-mikke — APPROVED** [review]
LGTM

**Comment by valenad1** [comment]
Test is green, merging

**Comment by valenad1** [comment]
I fixed the strange merge commit there.
